on: [push,workflow_dispatch]
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    name: AWS CDK Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure AWS credentials from Axelerant account
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::959068696076:role/aws-cdk-action
            aws-region: ap-northeast-2
      - name: install npm
        run: 'sudo apt update -y && sudo apt install nodejs npm -y'

      - name: Install AWS CDK
        run: 'sudo npm install -g aws-cdk' 

      - name: Install Requirements 
        run: 'pip3 install -r requirements.txt'
        working-directory: .

      - name: CDK Synth
        run: cdk synth
        working-directory: .
              
      - name: CDK bootstrap
        run: cdk bootstrap
        working-directory: .

      - name: CDK Deploy
        run: cdk deploy --all --require-approval never
        working-directory: .
